import React from 'react';
import ReactDOM from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import App from './App';
import './styles.css';

const root = ReactDOM.createRoot(document.getElementById('root')!);

// amplify_outputs.json is generated by `npx ampx sandbox` (local) or
// `npx ampx pipeline-deploy` (Amplify Hosting CI). import.meta.glob lets the
// app build even before the backend exists, so a fresh clone still compiles.
const outputModules = import.meta.glob<{ default: object }>('../amplify_outputs.json');
const loadOutputs = outputModules['../amplify_outputs.json'];

async function bootstrap() {
  if (!loadOutputs) {
    root.render(<NotConfigured />);
    return;
  }
  const outputs = (await loadOutputs()).default;
  Amplify.configure(outputs);
  root.render(
    <React.StrictMode>
      <App />
    </React.StrictMode>,
  );
}

function NotConfigured() {
  return (
    <div className="center-screen">
      <div className="card" style={{ maxWidth: 480 }}>
        <h1>Backend not configured</h1>
        <p>
          <code>amplify_outputs.json</code> was not found. Start the backend first:
        </p>
        <pre>npx ampx sandbox</pre>
        <p>then reload this page. See the README for full deployment steps.</p>
      </div>
    </div>
  );
}

void bootstrap();
